### ISSUE TITLE
Undefined index: Popup

### ISSUE THREAD

**Issue by RocoWayne** [HotshotHD/DropParty#1]
Im having this issue right now 

13.01 10:12:39 [Server] Server thread/NOTICE ArrayOutOfBoundsException: "Undefined index: Popup" (E_NOTICE) in "/DropParty_v1.0.1.phar/src/dropparty/task/DropItemsTask" at line 28
13.01 10:12:39 [Server] Server thread/CRITICAL Could not execute task dropparty\task\DropItemsTask: Undefined index: Popup
13.01 10:12:38 [Server] Server thread/NOTICE ArrayOutOfBoundsException: "Undefined index: Popup" (E_NOTICE) in "/DropParty_v1.0.1.phar/src/dropparty/task/DropItemsTask" at line 28
13.01 10:12:38 [Server] Server thread/CRITICAL Could not execute task dropparty\task\DropItemsTask: Undefined index: Popup

**Comment by RocoWayne** [comment]
can you help me? I reset the config, upgrade to the last version of Dropparty and still get this error

**Comment by dcrbrts** [comment]
I tried to submit a fix but I don't have access to this repository in GitHub.  Hopefully HotshotHD can knock this out for us soon.

The root cause of the error is that DropParty.php need to be updated to change the value "Popup" to be "Popup.Enabled" in line 28

if($this->getPlugin()->config()["Popup"] == true) {
if($this->getPlugin()->config()["Popup.Enabled"] == true) {

For a quick fix to get it running on your server, make the reverse change in the config.yml file as below (removing the .Enabled)...

Time: 1
Duration: 15
Message.Started: '[DropParty] Has started!'
Message.Ended: '[DropParty] Has ended!'
Message.Countdown: '[DropParty] Starting in {time} mins.'
**Popup**: true
Popup.Message: '[DropParty] Items are dropping!'
Coordinates:

That should get you running until the fix is published.

Cheers.

**Comment by RocoWayne** [comment]
oh, @drobertsc , thanks, i will try it later. Hope @HotshotHD take this and update the plugin, it was very usefull!

**Comment by dcrbrts** [comment]
I'm certain they will.  It's loads of fun when it's running!

**Comment by HotshotHD** [comment]
Sorry for the late reply. I've been pretty busy with school.
But thanks @drobertsc for helping him with the issue.
I updated the plugin to fix the issue also.

**Comment by dcrbrts** [comment]
Awesome, thanks!

**Comment by RocoWayne** [comment]
Works great again! :dancer:
